"""
Zerodha Kite Connect service — primary price source.

Uses Kite Connect v3 REST API directly (no SDK dependency).
Provides stock quotes, market indices, and instrument search.

Auth flow:
  1. User visits login URL (generated by get_login_url())
  2. Kite redirects with ?request_token=... to our callback
  3. We exchange request_token → access_token via generate_session()
  4. access_token is stored in .env / memory for subsequent calls

All API calls need: api_key + access_token (daily refresh required).
"""
import os
import json
import time
import hashlib
import threading
import requests
from typing import Optional, Dict, List, Tuple
import logging
from dotenv import load_dotenv

logger = logging.getLogger(__name__)

# ═══════════════════════════════════════════════════════════
#  CONFIG
# ═══════════════════════════════════════════════════════════

_ENV_PATH = os.path.join(os.path.dirname(__file__), "..", ".env")
load_dotenv(_ENV_PATH)

_BASE_URL = "https://api.kite.trade"
_LOGIN_URL = "https://kite.zerodha.com/connect/login"
_API_VERSION = "3"

_api_key: str = os.getenv("ZERODHA_API_KEY", "").strip()
_api_secret: str = os.getenv("ZERODHA_API_SECRET", "").strip()
_access_token: str = os.getenv("ZERODHA_ACCESS_TOKEN", "").strip()
_user_id: str = os.getenv("ZERODHA_USER_ID", "").strip()
_password: str = os.getenv("ZERODHA_PASSWORD", "").strip()
_totp_secret: str = os.getenv("ZERODHA_TOTP_SECRET", "").strip()

# Log what we loaded (masked)
if _api_key:
    logger.info(f"[Zerodha] API key loaded: {_api_key[:4]}...{_api_key[-4:]} ({len(_api_key)} chars)")
if _access_token:
    logger.info(f"[Zerodha] Access token loaded: {_access_token[:4]}...{_access_token[-4:]} ({len(_access_token)} chars)")

# Thread safety
_lock = threading.Lock()
_session_valid = False
_last_error = ""
_auth_failed = False  # Set True on 403 — stops retrying until token is refreshed
_conn_failed = False  # Set True on connection errors — retries once per refresh cycle
_conn_fail_time = 0.0  # When connection last failed (retry after 60s)

# Instrument cache: {"SYMBOL.EXCHANGE" → instrument_token}
_instrument_token_cache: Dict[str, int] = {}
_instrument_tokens_loaded = False
_instrument_tokens_lock = threading.Lock()

# Instrument name cache: {"SYMBOL.EXCHANGE" → "Company Name"}
_instrument_names: Dict[str, str] = {}
_instrument_names_loaded = False
_instrument_names_lock = threading.Lock()


def _headers() -> dict:
    """Build auth headers for Kite API."""
    return {
        "X-Kite-Version": _API_VERSION,
        "Authorization": f"token {_api_key}:{_access_token}",
    }


def _try_auto_login_and_retry(path: str, params: dict = None) -> Optional[dict]:
    """Attempt auto-login and retry the failed request."""
    if not can_auto_login() or _auto_login_in_progress:
        return None
    logger.info("[Zerodha] Attempting auto-login...")
    if auto_login():
        try:
            retry_resp = requests.get(
                f"{_BASE_URL}{path}",
                headers=_headers(),
                params=params,
                timeout=(5, 10),
            )
            if retry_resp.status_code == 200:
                return retry_resp.json()
        except Exception:
            pass
    return None


def _api_get(path: str, params: dict = None) -> Optional[dict]:
    """Make authenticated GET request to Kite API."""
    global _auth_failed, _last_error, _conn_failed, _conn_fail_time
    if not _api_key:
        return None
    # If no token or auth failed, try auto-login before giving up
    if not _access_token or _auth_failed:
        result = _try_auto_login_and_retry(path, params)
        if result is not None:
            return result
        return None
    # Skip if connection recently failed (retry after 10s)
    if _conn_failed and (time.time() - _conn_fail_time) < 10:
        return None
    max_retries = 2
    for attempt in range(max_retries):
        try:
            resp = requests.get(
                f"{_BASE_URL}{path}",
                headers=_headers(),
                params=params,
                timeout=(5, 15),  # (connect_timeout, read_timeout)
            )
            # Connection succeeded — reset conn_failed
            _conn_failed = False
            if resp.status_code == 200:
                _auth_failed = False  # Reset on success
                return resp.json()
            elif resp.status_code == 403:
                _auth_failed = True
                _last_error = f"Auth failed (403): {resp.text[:200]}"
                logger.error(f"[Zerodha] {_last_error}")
                with _lock:
                    global _session_valid
                    _session_valid = False
                # Try auto-login and retry
                result = _try_auto_login_and_retry(path, params)
                if result is not None:
                    return result
                logger.warning("[Zerodha] Token expired. Visit /api/zerodha/login to refresh.")
                return None
            elif resp.status_code == 429:
                # Rate limited — wait and retry
                if attempt < max_retries - 1:
                    time.sleep(1)
                    continue
                _last_error = f"Rate limited (429)"
                logger.warning(f"[Zerodha] {_last_error}")
                return None
            else:
                _last_error = f"API error {resp.status_code}: {resp.text[:100]}"
                logger.error(f"[Zerodha] {_last_error}")
                return None
        except requests.exceptions.RequestException as e:
            if attempt < max_retries - 1:
                time.sleep(0.5)
                continue
            _conn_failed = True
            _conn_fail_time = time.time()
            _last_error = f"Connection failed: {str(e)[:120]}"
            logger.error(f"[Zerodha] Request failed: {e}")
            return None


# ═══════════════════════════════════════════════════════════
#  AUTH
# ═══════════════════════════════════════════════════════════

def is_configured() -> bool:
    """Check if Zerodha API key is configured."""
    return bool(_api_key)


def is_session_valid() -> bool:
    """Check if we have a valid access token (and it hasn't been rejected).
    If session is invalid but auto-login credentials are available, attempts auto-login.
    """
    if _api_key and _access_token and not _auth_failed:
        return True
    # Try auto-login if credentials are available
    if can_auto_login() and not _auto_login_in_progress:
        logger.warning("[Zerodha] Session invalid — attempting auto-login...")
        if auto_login():
            return True
    return False


def get_login_url(redirect_url: str = "http://localhost:9999/api/zerodha/callback") -> str:
    """Get Kite login URL for user to authenticate."""
    return f"{_LOGIN_URL}?v={_API_VERSION}&api_key={_api_key}&redirect_url={redirect_url}"


def generate_session(request_token: str) -> bool:
    """Exchange request_token for access_token using API secret.
    Call this after user completes Kite login."""
    global _access_token, _session_valid, _auth_failed, _conn_failed
    if not _api_key or not _api_secret:
        logger.error("[Zerodha] API key or secret not configured")
        return False

    # Checksum: SHA-256 of (api_key + request_token + api_secret)
    checksum = hashlib.sha256(
        f"{_api_key}{request_token}{_api_secret}".encode()
    ).hexdigest()

    try:
        resp = requests.post(
            f"{_BASE_URL}/session/token",
            data={
                "api_key": _api_key,
                "request_token": request_token,
                "checksum": checksum,
            },
            timeout=10,
        )
        if resp.status_code == 200:
            data = resp.json().get("data", {})
            _access_token = data.get("access_token", "")
            if _access_token:
                # Reset all failure flags — we have a fresh valid token
                _auth_failed = False
                _conn_failed = False
                with _lock:
                    _session_valid = True
                # Persist to .env
                _update_env("ZERODHA_ACCESS_TOKEN", _access_token)
                logger.info(f"[Zerodha] Session created, token: {_access_token[:8]}...")
                return True
        logger.error(f"[Zerodha] Session failed: {resp.status_code} {resp.text[:200]}")
    except Exception as e:
        logger.error(f"[Zerodha] Session error: {e}")
    return False


def set_access_token(token: str):
    """Manually set access token (e.g. from frontend)."""
    global _access_token, _session_valid, _auth_failed, _conn_failed
    _access_token = token.strip()
    _auth_failed = False  # Reset — allow retrying with new token
    _conn_failed = False  # Reset connection failure too
    with _lock:
        _session_valid = bool(_access_token)
    if _access_token:
        _update_env("ZERODHA_ACCESS_TOKEN", _access_token)
        logger.info(f"[Zerodha] Access token set: {_access_token[:8]}...")


def _update_env(key: str, value: str):
    """Update a key in the .env file."""
    try:
        lines = []
        found = False
        if os.path.exists(_ENV_PATH):
            with open(_ENV_PATH) as f:
                for line in f:
                    if line.strip().startswith(f"{key}="):
                        lines.append(f"{key}={value}\n")
                        found = True
                    else:
                        lines.append(line)
        if not found:
            lines.append(f"{key}={value}\n")
        with open(_ENV_PATH, "w") as f:
            f.writelines(lines)
    except Exception as e:
        logger.error(f"[Zerodha] Failed to update .env: {e}")


# ═══════════════════════════════════════════════════════════
#  AUTO-LOGIN (TOTP-based)
# ═══════════════════════════════════════════════════════════

_auto_login_lock = threading.Lock()
_auto_login_in_progress = False


def can_auto_login() -> bool:
    """Check if we have credentials for automated login."""
    return bool(_api_key and _api_secret and _user_id and _password and _totp_secret)


def auto_login() -> bool:
    """Automatically login to Zerodha using stored credentials + TOTP.

    Flow:
      1. POST kite.zerodha.com/api/login with user_id + password → request_id
      2. Generate TOTP code from secret
      3. POST kite.zerodha.com/api/twofa with request_id + totp → session
      4. GET connect/login URL with session cookies → redirect with request_token
      5. Exchange request_token → access_token via generate_session()

    Returns True if new access_token was obtained.
    """
    global _auto_login_in_progress, _access_token, _session_valid, _auth_failed, _conn_failed

    if not can_auto_login():
        logger.warning("[Zerodha] Auto-login not possible — missing credentials")
        return False

    with _auto_login_lock:
        if _auto_login_in_progress:
            return False
        _auto_login_in_progress = True

    try:
        import pyotp
        session = requests.Session()

        # Step 1: Login with user_id + password
        logger.info("[Zerodha] Auto-login: posting credentials...")
        login_resp = session.post(
            "https://kite.zerodha.com/api/login",
            data={"user_id": _user_id, "password": _password},
            timeout=15,
        )
        if login_resp.status_code != 200:
            logger.error(f"[Zerodha] Auto-login: login failed ({login_resp.status_code}): {login_resp.text[:200]}")
            return False

        login_data = login_resp.json()
        request_id = login_data.get("data", {}).get("request_id", "")
        if not request_id:
            logger.error(f"[Zerodha] Auto-login: no request_id in response: {login_data}")
            return False

        # Step 2: Generate TOTP and submit 2FA
        totp = pyotp.TOTP(_totp_secret)
        totp_code = totp.now()
        logger.info("[Zerodha] Auto-login: submitting TOTP...")

        # Use the 2FA type from login response (usually "app_code" for TOTP)
        twofa_type = login_data.get("data", {}).get("twofa_type", "app_code")
        twofa_resp = session.post(
            "https://kite.zerodha.com/api/twofa",
            data={
                "user_id": _user_id,
                "request_id": request_id,
                "twofa_value": totp_code,
                "twofa_type": twofa_type,
            },
            timeout=15,
        )
        if twofa_resp.status_code != 200:
            logger.error(f"[Zerodha] Auto-login: 2FA failed ({twofa_resp.status_code}): {twofa_resp.text[:200]}")
            return False

        # Step 3: Hit the Kite Connect login URL with session cookies
        # Follow redirects manually — stop before hitting our local callback
        # (which may be unreachable inside Docker or on a different port)
        connect_url = f"https://kite.zerodha.com/connect/login?v={_API_VERSION}&api_key={_api_key}"
        logger.info("[Zerodha] Auto-login: fetching connect login for request_token...")

        from urllib.parse import urlparse, parse_qs
        connect_resp = session.get(connect_url, allow_redirects=False, timeout=15)
        request_token = None
        for _ in range(10):  # max redirects
            location = connect_resp.headers.get("Location", "")
            parsed = urlparse(location)
            params = parse_qs(parsed.query)
            if "request_token" in params:
                request_token = params["request_token"][0]
                break
            if not location or connect_resp.status_code not in (301, 302, 303, 307, 308):
                break
            connect_resp = session.get(location, allow_redirects=False, timeout=15)
        # Fallback: check final URL if we followed all redirects
        if not request_token:
            parsed = urlparse(connect_resp.url)
            params = parse_qs(parsed.query)
            request_token = params.get("request_token", [None])[0]

        if not request_token:
            logger.error(f"[Zerodha] Auto-login: request_token not found in redirects: {connect_resp.url[:200]}")
            return False

        # Step 4: Exchange request_token for access_token
        logger.info("[Zerodha] Auto-login: exchanging request_token for access_token...")
        success = generate_session(request_token)
        if success:
            logger.info("[Zerodha] Auto-login: SUCCESS — new access token obtained")
        else:
            logger.error("[Zerodha] Auto-login: token exchange failed")
        return success

    except Exception as e:
        logger.error(f"[Zerodha] Auto-login error: {e}")
        return False
    finally:
        with _auto_login_lock:
            _auto_login_in_progress = False


# ═══════════════════════════════════════════════════════════
#  STOCK QUOTES
# ═══════════════════════════════════════════════════════════

# ── Symbol mapping: xlsx symbol → correct Kite trading symbol ──
# Some stocks have different trading symbols on exchanges than what's
# stored in our xlsx files (due to name changes, demergers, IPO symbols, etc.)
_KITE_SYMBOL_MAP: Dict[str, str] = {
    # BSE symbol truncated (BSE uses max 10 chars)
    "HIGHENERGY.BSE": "BSE:HIGHENE",
    # Historical file still named "Majesco Ltd.xlsx" but company renamed to Aurum
    "MAJESCO.NSE": "NSE:AURUM",
    # SBI ETF Gold: xlsx has NSE:SBIETF but Kite uses SETFGOLD
    "SBIETF.NSE": "NSE:SETFGOLD",
    "SBIETF.BSE": "BSE:SETFGOLD",
    # Nippon Life India AMC: xlsx has NIPPONAMC but Kite uses NAM-INDIA
    "NIPPONAMC.NSE": "NSE:NAM-INDIA",
    "NIPPONAMC.BSE": "BSE:NAM-INDIA",
}


def _kite_instrument(symbol: str, exchange: str) -> str:
    """Convert symbol + exchange to Kite instrument key.
    Checks the override map first, then falls back to EXCHANGE:SYMBOL.
    e.g. ('RELIANCE', 'NSE') → 'NSE:RELIANCE'
         ('MAJESCO', 'NSE') → 'NSE:AURUM' (from override map)
    """
    sym = symbol.upper()
    exch = exchange.upper()
    if exch not in ("BSE", "NSE"):
        exch = "NSE"

    # Check override map
    lookup_key = f"{sym}.{exch}"
    if lookup_key in _KITE_SYMBOL_MAP:
        return _KITE_SYMBOL_MAP[lookup_key]

    return f"{exch}:{sym}"


def fetch_ltp(symbols: List[Tuple[str, str]]) -> Dict[str, float]:
    """Fetch Last Traded Price for multiple instruments.
    Returns {symbol.exchange: price}."""
    if not is_session_valid():
        return {}

    # Build instrument list: i=NSE:RELIANCE&i=BSE:TCS
    # Use list of keys (not single) to handle multiple symbols → same Kite instrument
    seen_instruments = set()
    instruments = []
    inst_to_keys: Dict[str, List[str]] = {}  # kite_inst → [sym.exch, ...]
    for sym, exch in symbols:
        inst = _kite_instrument(sym, exch)
        key = f"{sym}.{exch}"
        inst_to_keys.setdefault(inst, []).append(key)
        if inst not in seen_instruments:
            instruments.append(inst)
            seen_instruments.add(inst)

    # Kite allows up to 500 instruments per LTP call
    results: Dict[str, float] = {}
    batch_size = 500
    for i in range(0, len(instruments), batch_size):
        batch = instruments[i:i + batch_size]
        params = [("i", inst) for inst in batch]
        data = _api_get("/quote/ltp", params)
        if data and "data" in data:
            for inst_key, info in data["data"].items():
                mapped_keys = inst_to_keys.get(inst_key, [])
                if mapped_keys and info.get("last_price", 0) > 0:
                    price = float(info["last_price"])
                    for mk in mapped_keys:
                        results[mk] = price

    return results


def fetch_quotes(symbols: List[Tuple[str, str]]) -> Dict[str, dict]:
    """Fetch full quotes (price, OHLC, volume, 52wk range) for multiple instruments.
    Returns {symbol.exchange: {price, open, high, low, close, volume, ...}}."""
    if not is_session_valid():
        return {}

    seen_instruments = set()
    instruments = []
    inst_to_keys: Dict[str, List[str]] = {}
    for sym, exch in symbols:
        inst = _kite_instrument(sym, exch)
        key = f"{sym}.{exch}"
        inst_to_keys.setdefault(inst, []).append(key)
        if inst not in seen_instruments:
            instruments.append(inst)
            seen_instruments.add(inst)

    results: Dict[str, dict] = {}
    batch_size = 500
    for i in range(0, len(instruments), batch_size):
        batch = instruments[i:i + batch_size]
        params = [("i", inst) for inst in batch]
        data = _api_get("/quote", params)
        if not data or "data" not in data:
            # Retry failed batch once
            logger.warning(f"[Zerodha] Quote batch {i//batch_size + 1} failed, retrying...")
            time.sleep(0.5)
            data = _api_get("/quote", params)
        if data and "data" in data:
            for inst_key, info in data["data"].items():
                mapped_keys = inst_to_keys.get(inst_key, [])
                if not mapped_keys:
                    continue
                ltp = float(info.get("last_price", 0))
                if ltp <= 0:
                    continue

                ohlc = info.get("ohlc", {})
                prev_close = float(ohlc.get("close", 0))
                day_change = ltp - prev_close if prev_close > 0 else 0
                day_change_pct = (day_change / prev_close * 100) if prev_close > 0 else 0

                quote_data = {
                    "price": round(ltp, 2),
                    "open": float(ohlc.get("open", 0)),
                    "high": float(ohlc.get("high", 0)),
                    "low": float(ohlc.get("low", 0)),
                    "close": prev_close,
                    "volume": int(info.get("volume", 0) or 0),
                    "day_change": round(day_change, 2),
                    "day_change_pct": round(day_change_pct, 2),
                    "lower_circuit": float(info.get("lower_circuit_limit", 0) or 0),
                    "upper_circuit": float(info.get("upper_circuit_limit", 0) or 0),
                    # NOTE: Kite /quote does NOT provide 52-week data.
                    # ohlc.high/low is TODAY's daily high/low — NOT 52-week.
                    # 52-week is fetched separately via fetch_52_week_range().
                    "week_52_high": 0,
                    "week_52_low": 0,
                    "name": "",  # Kite doesn't return company name in quotes
                }
                for mk in mapped_keys:
                    results[mk] = quote_data

    return results


def fetch_ohlc(symbols: List[Tuple[str, str]]) -> Dict[str, dict]:
    """Fetch OHLC + LTP for multiple instruments (lighter than full quote).
    Returns {symbol.exchange: {price, open, high, low, close, volume}}."""
    if not is_session_valid():
        return {}

    seen_instruments = set()
    instruments = []
    inst_to_keys: Dict[str, List[str]] = {}
    for sym, exch in symbols:
        inst = _kite_instrument(sym, exch)
        key = f"{sym}.{exch}"
        inst_to_keys.setdefault(inst, []).append(key)
        if inst not in seen_instruments:
            instruments.append(inst)
            seen_instruments.add(inst)

    results: Dict[str, dict] = {}
    batch_size = 500
    for i in range(0, len(instruments), batch_size):
        batch = instruments[i:i + batch_size]
        params = [("i", inst) for inst in batch]
        data = _api_get("/quote/ohlc", params)
        if data and "data" in data:
            for inst_key, info in data["data"].items():
                mapped_keys = inst_to_keys.get(inst_key, [])
                if not mapped_keys:
                    continue
                ltp = float(info.get("last_price", 0))
                if ltp <= 0:
                    continue
                ohlc = info.get("ohlc", {})
                ohlc_data = {
                    "price": round(ltp, 2),
                    "open": float(ohlc.get("open", 0)),
                    "high": float(ohlc.get("high", 0)),
                    "low": float(ohlc.get("low", 0)),
                    "close": float(ohlc.get("close", 0)),
                    "volume": 0,  # Not in OHLC response
                }
                for mk in mapped_keys:
                    results[mk] = ohlc_data

    return results


# ═══════════════════════════════════════════════════════════
#  52-WEEK HIGH/LOW  (via Historical Data API)
# ═══════════════════════════════════════════════════════════

# Cache: {"SYMBOL.EXCHANGE" → {week_52_high, week_52_low, fetched_at}}
_52w_cache: Dict[str, dict] = {}
_52w_cache_lock = threading.Lock()
_52W_CACHE_TTL = 6 * 3600  # Refresh 52-week data every 6 hours


def clear_52w_cache():
    """Clear the 52-week/SMA cache so next fetch recomputes from scratch."""
    with _52w_cache_lock:
        _52w_cache.clear()


def _get_instrument_token(symbol: str, exchange: str) -> Optional[int]:
    """Look up Kite instrument_token for a symbol. Loads instruments if needed."""
    if not _instrument_tokens_loaded:
        _load_instruments()
    key = f"{symbol.upper()}.{exchange.upper()}"
    token = _instrument_token_cache.get(key)
    if token is None and key in _KITE_SYMBOL_MAP:
        # Try alias: e.g. SBIETF.NSE → SETFGOLD.NSE
        mapped = _KITE_SYMBOL_MAP[key]  # "NSE:SETFGOLD"
        exch2, sym2 = mapped.split(":", 1)
        token = _instrument_token_cache.get(f"{sym2}.{exch2}")
    return token


def _fetch_historical_52w(instrument_token: int) -> Optional[dict]:
    """Fetch 1 year of daily candles and compute 52-week high/low + 7d/30d changes.
    Returns {week_52_high, week_52_low, week_change_pct, month_change_pct} or None.

    Kite Historical Data API:
      GET /instruments/historical/{token}/day?from=YYYY-MM-DD&to=YYYY-MM-DD
      Response: {"data":{"candles":[[ts,open,high,low,close,volume],...]}}
    """
    from datetime import datetime, timedelta
    now = datetime.now()
    to_date = now.strftime("%Y-%m-%d")
    from_date = (now - timedelta(days=365)).strftime("%Y-%m-%d")

    path = f"/instruments/historical/{instrument_token}/day"
    data = _api_get(path, {"from": from_date, "to": to_date})
    if not data or "data" not in data:
        return None
    candles = data["data"].get("candles", [])
    if not candles:
        return None

    # Candle format: [timestamp, open, high, low, close, volume]
    highs = [c[2] for c in candles if len(c) >= 4]
    lows = [c[3] for c in candles if len(c) >= 4]
    if not highs or not lows:
        return None

    latest_close = candles[-1][4] if len(candles[-1]) >= 5 else 0

    # Find close price ~7 and ~30 calendar days ago
    week_change_pct = 0.0
    month_change_pct = 0.0
    if latest_close > 0:
        target_7d = now - timedelta(days=7)
        target_30d = now - timedelta(days=30)
        close_7d = 0.0
        close_30d = 0.0
        for c in candles:
            try:
                ts = c[0][:10] if isinstance(c[0], str) else c[0].strftime("%Y-%m-%d") if hasattr(c[0], 'strftime') else str(c[0])[:10]
                candle_date = datetime.strptime(ts, "%Y-%m-%d")
            except (ValueError, TypeError, AttributeError):
                continue
            if candle_date <= target_7d:
                close_7d = c[4] if len(c) >= 5 else 0
            if candle_date <= target_30d:
                close_30d = c[4] if len(c) >= 5 else 0
        if close_7d > 0:
            week_change_pct = round((latest_close - close_7d) / close_7d * 100, 2)
        if close_30d > 0:
            month_change_pct = round((latest_close - close_30d) / close_30d * 100, 2)

    # SMA & Bull/Bear signal calculation
    closes = [c[4] for c in candles if len(c) >= 5]
    n = len(closes)

    # Compute both 50-SMA and 200-SMA (adaptive for short histories)
    sma_50 = round(sum(closes[-50:]) / 50, 2) if n >= 50 else (round(sum(closes[-20:]) / 20, 2) if n >= 20 else None)
    sma_200 = round(sum(closes[-200:]) / 200, 2) if n >= 200 else (round(sum(closes[-50:]) / 50, 2) if n >= 50 else None)

    # Bull/Bear signal: 50-SMA vs 200-SMA + Price vs 200-SMA
    signal = None
    if sma_50 is not None and sma_200 is not None and latest_close > 0:
        if sma_50 > sma_200 and latest_close > sma_200:
            signal = "strong_bull"
        elif sma_50 > sma_200 and latest_close < sma_200:
            signal = "weak_bull"
        elif sma_50 < sma_200 and latest_close > sma_200:
            signal = "weak_bear"
        else:
            signal = "strong_bear"

    # Count consecutive days price has been below 50-SMA (walking backwards)
    below_sma_n = 50 if n >= 50 else (20 if n >= 20 else 0)
    days_below_sma = 0
    if below_sma_n > 0 and n >= below_sma_n:
        for i in range(n - 1, below_sma_n - 2, -1):
            sma_at_i = sum(closes[i - below_sma_n + 1:i + 1]) / below_sma_n
            if closes[i] < sma_at_i:
                days_below_sma += 1
            else:
                break

    # RSI (14-day) calculation
    rsi = None
    if n >= 15:
        changes = [closes[i] - closes[i-1] for i in range(-14, 0)]
        gains = [c for c in changes if c > 0]
        losses = [-c for c in changes if c < 0]
        avg_gain = sum(gains) / 14 if gains else 0
        avg_loss = sum(losses) / 14 if losses else 0
        if avg_loss > 0:
            rs = avg_gain / avg_loss
            rsi = round(100 - (100 / (1 + rs)), 1)
        elif avg_gain > 0:
            rsi = 100.0

    return {
        "week_52_high": max(highs),
        "week_52_low": min(lows),
        "week_change_pct": week_change_pct,
        "month_change_pct": month_change_pct,
        "sma_50": sma_50,
        "sma_200": sma_200,
        "signal": signal,
        "days_below_sma": days_below_sma,
        "rsi": rsi,
    }


def fetch_52_week_range(symbols: List[Tuple[str, str]]) -> Dict[str, dict]:
    """Fetch 52-week high/low for multiple stocks using Kite Historical Data API.

    Returns {symbol.exchange: {week_52_high: float, week_52_low: float}}.
    Uses a 6-hour cache TTL to avoid excessive API calls.
    Rate-limited to ~3 requests/second (Kite historical API limit).
    """
    if not is_session_valid():
        return {}

    results: Dict[str, dict] = {}
    need_fetch: List[Tuple[str, str, int]] = []  # (sym, exch, token)

    now = time.time()

    # Check cache first
    for sym, exch in symbols:
        key = f"{sym}.{exch}"
        with _52w_cache_lock:
            cached = _52w_cache.get(key)
        if cached and (now - cached.get("fetched_at", 0)) < _52W_CACHE_TTL:
            # Serve existing data immediately
            results[key] = {
                "week_52_high": cached["week_52_high"],
                "week_52_low": cached["week_52_low"],
                "week_change_pct": cached.get("week_change_pct", 0.0),
                "month_change_pct": cached.get("month_change_pct", 0.0),
                "sma_50": cached.get("sma_50"),
                "sma_200": cached.get("sma_200"),
                "signal": cached.get("signal"),
                "days_below_sma": cached.get("days_below_sma", 0),
                "rsi": cached.get("rsi"),
            }
            continue

        # Need to fetch — look up instrument token
        token = _get_instrument_token(sym, exch)
        if token:
            need_fetch.append((sym, exch, token))

    if not need_fetch:
        return results

    logger.info(f"[Zerodha] Fetching 52-week range for {len(need_fetch)} stocks via Historical API...")
    fetched = 0
    failed = 0

    # Use thread pool for parallel fetches (3 workers to stay within rate limits)
    from concurrent.futures import ThreadPoolExecutor, as_completed
    _rate_lock = threading.Lock()
    _last_req_time = [0.0]

    def _fetch_one(sym, exch, token):
        # Throttle: minimum 0.35s between requests
        with _rate_lock:
            elapsed = time.time() - _last_req_time[0]
            if elapsed < 0.35:
                time.sleep(0.35 - elapsed)
            _last_req_time[0] = time.time()
        key = f"{sym}.{exch}"
        try:
            result = _fetch_historical_52w(token)
            return (key, result)
        except Exception as e:
            logger.error(f"[Zerodha] 52w fetch error for {key}: {e}")
            return (key, None)

    with ThreadPoolExecutor(max_workers=3) as executor:
        futures = {executor.submit(_fetch_one, sym, exch, token): (sym, exch) for sym, exch, token in need_fetch}
        for future in as_completed(futures):
            key, result = future.result()
            if result:
                entry = {
                    "week_52_high": round(result["week_52_high"], 2),
                    "week_52_low": round(result["week_52_low"], 2),
                    "week_change_pct": result.get("week_change_pct", 0.0),
                    "month_change_pct": result.get("month_change_pct", 0.0),
                    "sma_50": result.get("sma_50"),
                    "sma_200": result.get("sma_200"),
                    "signal": result.get("signal"),
                    "days_below_sma": result.get("days_below_sma", 0),
                    "rsi": result.get("rsi"),
                    "fetched_at": now,
                }
                with _52w_cache_lock:
                    _52w_cache[key] = entry
                results[key] = {
                    "week_52_high": entry["week_52_high"],
                    "week_52_low": entry["week_52_low"],
                    "week_change_pct": entry["week_change_pct"],
                    "month_change_pct": entry["month_change_pct"],
                    "sma_50": entry["sma_50"],
                    "sma_200": entry["sma_200"],
                    "signal": entry["signal"],
                    "days_below_sma": entry["days_below_sma"],
                    "rsi": entry["rsi"],
                }
                fetched += 1
            else:
                failed += 1

    logger.info(f"[Zerodha] 52-week range: {fetched} fetched, {failed} failed")
    return results


# ═══════════════════════════════════════════════════════════
#  MARKET TICKERS (Indices, Forex, Commodities)
# ═══════════════════════════════════════════════════════════


def _get_near_month_suffixes() -> List[str]:
    """Get YY+MMM suffixes for current month, next month, and month after.
    e.g. ['26FEB', '26MAR', '26APR'] for Feb 2026."""
    from datetime import datetime, timedelta
    now = datetime.now()
    suffixes = []
    for offset_months in range(3):
        dt = now.replace(day=1)
        for _ in range(offset_months):
            dt = (dt + timedelta(days=32)).replace(day=1)
        suffixes.append(f"{dt.strftime('%y')}{dt.strftime('%b').upper()}")
    return suffixes


def _build_ticker_candidates() -> Dict[str, List[str]]:
    """Build candidate Kite instruments for each market ticker key.
    Tries current month, next month for futures contracts.
    Returns {ticker_key: [candidate1, candidate2, ...]}"""
    suffixes = _get_near_month_suffixes()
    s0, s1, s2 = suffixes[0], suffixes[1], suffixes[2]

    return {
        # Indices — fixed names, always available
        "SENSEX":   ["BSE:SENSEX"],
        "NIFTY50":  ["NSE:NIFTY 50"],
        "GIFTNIFTY": [f"NFO:NIFTY{s0}FUT", f"NFO:NIFTY{s1}FUT"],

        # Currency derivatives (CDS segment on NSE)
        "USDINR":   [f"CDS:USDINR{s0}FUT", f"CDS:USDINR{s1}FUT"],

        # MCX Commodities — near-month futures
        # Crude Oil: monthly contracts
        "CRUDEOIL": [f"MCX:CRUDEOIL{s0}FUT", f"MCX:CRUDEOIL{s1}FUT",
                     f"MCX:CRUDEOILM{s0}FUT", f"MCX:CRUDEOILM{s1}FUT"],
        # Gold: bi-monthly (Feb, Apr, Jun, Aug, Oct, Dec) + Gold Mini (monthly)
        "GOLD":     [f"MCX:GOLD{s0}FUT", f"MCX:GOLD{s1}FUT", f"MCX:GOLD{s2}FUT",
                     f"MCX:GOLDM{s0}FUT", f"MCX:GOLDM{s1}FUT",
                     f"MCX:GOLDPETAL{s0}FUT", f"MCX:GOLDPETAL{s1}FUT"],
        # Silver: monthly + Silver Mini
        "SILVER":   [f"MCX:SILVER{s0}FUT", f"MCX:SILVER{s1}FUT",
                     f"MCX:SILVERM{s0}FUT", f"MCX:SILVERM{s1}FUT",
                     f"MCX:SILVERMIC{s0}FUT", f"MCX:SILVERMIC{s1}FUT"],

        # International — not available on Indian exchanges via Kite
        "SGX":      [],
        "NIKKEI":   [],
        "SGDINR":   [],
    }


def fetch_market_tickers() -> Dict[str, dict]:
    """Fetch market ticker data from Kite (indices + forex + MCX commodities).
    Uses dynamic near-month contract names for futures.
    Returns {key: {price, change, change_pct}} for available instruments."""
    if not is_session_valid():
        return {}

    candidates = _build_ticker_candidates()

    # Collect ALL candidate instruments into a single API call
    all_instruments = []
    inst_to_ticker: Dict[str, str] = {}  # kite_inst → ticker_key
    inst_priority: Dict[str, int] = {}   # kite_inst → priority (lower = better)
    for ticker_key, cands in candidates.items():
        for idx, kite_inst in enumerate(cands):
            all_instruments.append(kite_inst)
            inst_to_ticker[kite_inst] = ticker_key
            inst_priority[kite_inst] = idx

    if not all_instruments:
        return {}

    # One API call with all candidates
    params = [("i", inst) for inst in all_instruments]
    data = _api_get("/quote", params)
    if not data or "data" not in data:
        return {}

    # Parse responses, pick best candidate per ticker (lowest priority index)
    ticker_results: Dict[str, Tuple[int, dict]] = {}  # key → (priority, data)
    for inst_key, info in data["data"].items():
        ticker_key = inst_to_ticker.get(inst_key, "")
        if not ticker_key:
            continue
        ltp = float(info.get("last_price", 0))
        if ltp <= 0:
            continue
        priority = inst_priority.get(inst_key, 999)

        # Only keep the highest-priority (lowest idx) result per ticker
        existing = ticker_results.get(ticker_key)
        if existing and existing[0] <= priority:
            continue

        ohlc = info.get("ohlc", {})
        prev_close = float(ohlc.get("close", 0))
        change = ltp - prev_close if prev_close > 0 else 0
        pct = (change / prev_close * 100) if prev_close > 0 else 0
        ticker_results[ticker_key] = (priority, {
            "price": round(ltp, 2),
            "change": round(change, 2),
            "change_pct": round(pct, 2),
            "instrument": inst_key,
            "instrument_token": info.get("instrument_token"),
        })

    # Flatten: drop priority, keep just the data
    results: Dict[str, dict] = {}
    for key, (_, ticker_data) in ticker_results.items():
        results[key] = ticker_data
        logger.info(f"[Zerodha] Ticker {key} → {ticker_data['instrument']} "
              f"({ticker_data['price']})")

    return results


# ── Ticker 7D/1M historical changes (via Kite Historical API) ──

_ticker_hist_cache: Dict[str, dict] = {}  # key → {week_change_pct, month_change_pct, fetched_at}
_ticker_hist_lock = threading.Lock()
_TICKER_HIST_TTL = 6 * 3600  # 6 hours


def fetch_ticker_historical_changes(ticker_data: Dict[str, dict]) -> Dict[str, dict]:
    """Compute 1D/7D/1M changes for market tickers using Kite Historical Data API.

    Args:
        ticker_data: {key: {instrument_token, price, ...}} from fetch_market_tickers()

    Returns:
        {key: {day_change, day_change_pct, week_change_pct, month_change_pct}}
    """
    if not is_session_valid():
        return {}

    from datetime import datetime, timedelta
    now = datetime.now()
    now_ts = time.time()
    results: Dict[str, dict] = {}

    for key, data in ticker_data.items():
        token = data.get("instrument_token")
        if not token:
            continue

        # Check cache
        with _ticker_hist_lock:
            cached = _ticker_hist_cache.get(key)
            if cached and (now_ts - cached.get("fetched_at", 0)) < _TICKER_HIST_TTL:
                results[key] = {
                    "prev_day_close": cached.get("prev_day_close", 0.0),
                    "week_change_pct": cached["week_change_pct"],
                    "month_change_pct": cached["month_change_pct"],
                }
                continue

        # Fetch 35 days of daily candles
        to_date = now.strftime("%Y-%m-%d")
        from_date = (now - timedelta(days=35)).strftime("%Y-%m-%d")
        path = f"/instruments/historical/{token}/day"
        hist = _api_get(path, {"from": from_date, "to": to_date})
        if not hist or "data" not in hist:
            continue

        candles = hist["data"].get("candles", [])
        if not candles:
            continue

        # Apply divisor so historical candle prices match the displayed price scale
        divisor = data.get("divisor", 1) or 1

        latest_close = candles[-1][4] / divisor if len(candles[-1]) >= 5 else 0
        if latest_close <= 0:
            continue

        # Use current LTP if available (more accurate during market hours)
        current_price = data.get("price", latest_close) or latest_close

        # Find prev_day_close: the close of the trading day BEFORE the most recent one
        # This ensures 1D change works both during and after market hours.
        # During market hours: last candle = yesterday → prev = day-before-yesterday
        #   But current_price is live LTP, so 1D = LTP - yesterday's close (good)
        # After market hours: last candle = today → prev = yesterday
        #   And current_price = today's close, so 1D = today's close - yesterday's close (good)
        # We find the last two unique trading day closes from candles.
        recent_closes = []  # [(date_str, close_price), ...] most recent first
        seen_dates = set()
        for c in reversed(candles):
            try:
                ts = c[0][:10] if isinstance(c[0], str) else str(c[0])[:10]
            except (TypeError, AttributeError):
                continue
            if ts not in seen_dates and len(c) >= 5 and c[4] > 0:
                recent_closes.append((ts, c[4] / divisor))
                seen_dates.add(ts)
                if len(recent_closes) >= 2:
                    break

        prev_day_close = recent_closes[1][1] if len(recent_closes) >= 2 else 0.0

        target_7d = now - timedelta(days=7)
        target_30d = now - timedelta(days=30)
        close_7d = 0.0
        close_30d = 0.0

        for c in candles:
            try:
                ts = c[0][:10] if isinstance(c[0], str) else str(c[0])[:10]
                candle_date = datetime.strptime(ts, "%Y-%m-%d")
            except (ValueError, TypeError, AttributeError):
                continue
            if candle_date <= target_7d:
                close_7d = (c[4] / divisor) if len(c) >= 5 else 0
            if candle_date <= target_30d:
                close_30d = (c[4] / divisor) if len(c) >= 5 else 0

        week_pct = round((current_price - close_7d) / close_7d * 100, 2) if close_7d > 0 else 0.0
        month_pct = round((current_price - close_30d) / close_30d * 100, 2) if close_30d > 0 else 0.0

        result = {"prev_day_close": prev_day_close, "week_change_pct": week_pct, "month_change_pct": month_pct}
        results[key] = result

        with _ticker_hist_lock:
            _ticker_hist_cache[key] = {**result, "fetched_at": now_ts}

        time.sleep(0.35)  # Rate limit: ~3 req/sec

    return results


# ═══════════════════════════════════════════════════════════
#  INSTRUMENT NAME LOOKUP
# ═══════════════════════════════════════════════════════════

def _load_instruments():
    """Download instrument CSVs from Kite (NSE + BSE equity) and cache names + tokens.
    The /instruments/{exchange} endpoint returns a CSV with columns:
    instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,
    strike,tick_size,lot_size,instrument_type,segment,exchange
    """
    global _instrument_names_loaded, _instrument_tokens_loaded
    import csv
    import io

    if not _api_key or not _access_token:
        return

    with _instrument_names_lock:
        if _instrument_names_loaded:
            return

    names: Dict[str, str] = {}
    tokens: Dict[str, int] = {}
    for exchange in ("NSE", "BSE"):
        try:
            resp = requests.get(
                f"{_BASE_URL}/instruments/{exchange}",
                headers=_headers(),
                timeout=(5, 30),
            )
            if resp.status_code != 200:
                logger.error(f"[Zerodha] Instruments {exchange} failed: {resp.status_code}")
                continue
            reader = csv.DictReader(io.StringIO(resp.text))
            count = 0
            for row in reader:
                segment = row.get("segment", "")
                # Only equity instruments (skip F&O, CDS, etc.)
                if segment not in (f"{exchange}", f"{exchange}-EQ"):
                    continue
                sym = row.get("tradingsymbol", "").strip()
                name = row.get("name", "").strip()
                token_str = row.get("instrument_token", "").strip()
                if sym and name:
                    key = f"{sym}.{exchange}"
                    names[key] = name
                    if token_str:
                        try:
                            tokens[key] = int(token_str)
                        except ValueError:
                            pass
                    count += 1
            logger.info(f"[Zerodha] Loaded {count} {exchange} instrument names + tokens")
        except Exception as e:
            logger.error(f"[Zerodha] Instruments {exchange} error: {e}")

    with _instrument_names_lock:
        _instrument_names.update(names)
        _instrument_names_loaded = True
    with _instrument_tokens_lock:
        _instrument_token_cache.update(tokens)
        _instrument_tokens_loaded = True
    logger.info(f"[Zerodha] Total cached: {len(_instrument_names)} names, {len(_instrument_token_cache)} tokens")


def load_instruments_async():
    """Load instruments in a background thread (call at startup)."""
    t = threading.Thread(target=_load_instruments, daemon=True)
    t.start()


def lookup_instrument_name(symbol: str, exchange: str = "NSE") -> str:
    """Look up company name for a symbol from cached instruments.
    Returns empty string if not found."""
    if not _instrument_names_loaded:
        _load_instruments()  # Blocking load on first call if not yet loaded
    key = f"{symbol.upper()}.{exchange.upper()}"
    return _instrument_names.get(key, "")


def search_instruments(query: str, exchange: str = "", limit: int = 50) -> list:
    """Search instruments by symbol or name prefix.
    Returns up to `limit` matches: [{symbol, name, exchange}]."""
    if not _instrument_names_loaded:
        _load_instruments()
    q = query.upper().strip()
    if not q:
        return []
    results = []
    for key, name in _instrument_names.items():
        sym, exch = key.rsplit(".", 1)
        if exchange and exch != exchange.upper():
            continue
        if sym.startswith(q) or q in name.upper():
            results.append({"symbol": sym, "name": name, "exchange": exch})
            if len(results) >= limit:
                break
    # Sort: exact prefix matches first, then alphabetical
    results.sort(key=lambda r: (0 if r["symbol"].startswith(q) else 1, r["symbol"]))
    return results


# ═══════════════════════════════════════════════════════════
#  MUTUAL FUND INSTRUMENTS
# ═══════════════════════════════════════════════════════════

# MF instrument cache: [{tradingsymbol, amc, name, last_price, last_price_date}, ...]
_mf_instruments: List[dict] = []
_mf_instruments_loaded = False
_mf_instruments_lock = threading.Lock()


def _load_mf_instruments():
    """Download MF instruments from Kite: GET /mf/instruments (CSV).
    Fields: tradingsymbol, amc, name, purchase_allowed, redemption_allowed,
    minimum_purchase_amount, ..., last_price, last_price_date
    """
    global _mf_instruments_loaded
    import csv
    import io

    if not _api_key or not _access_token:
        return

    with _mf_instruments_lock:
        if _mf_instruments_loaded:
            return

    try:
        resp = requests.get(
            f"{_BASE_URL}/mf/instruments",
            headers=_headers(),
            timeout=(5, 30),
        )
        if resp.status_code != 200:
            logger.error(f"[Zerodha] MF instruments failed: {resp.status_code}")
            return
        reader = csv.DictReader(io.StringIO(resp.text))
        instruments = []
        for row in reader:
            instruments.append({
                "tradingsymbol": row.get("tradingsymbol", "").strip(),
                "amc": row.get("amc", "").strip(),
                "name": row.get("name", "").strip(),
                "scheme_type": row.get("scheme_type", "").strip(),
                "plan": row.get("plan", "").strip(),
                "dividend_type": row.get("dividend_type", "").strip(),
                "last_price": float(row.get("last_price", 0) or 0),
                "last_price_date": row.get("last_price_date", "").strip(),
            })
        with _mf_instruments_lock:
            _mf_instruments.clear()
            _mf_instruments.extend(instruments)
            _mf_instruments_loaded = True
        logger.info(f"[Zerodha] Loaded {len(instruments)} MF instruments")
    except Exception as e:
        logger.error(f"[Zerodha] MF instruments error: {e}")


def search_mf_instruments(query: str, plan: str = "direct", scheme_type: str = "") -> list:
    """Search mutual fund instruments by name with optional filters.
    plan: 'direct', 'regular', or '' (all)
    scheme_type: 'growth', 'dividend', or '' (all)
    Returns up to 15 matches."""
    if not _mf_instruments_loaded:
        _load_mf_instruments()
    q = query.upper().strip()
    if not q or len(q) < 2:
        return []
    words = q.split()
    plan_filter = plan.lower().strip()
    type_filter = scheme_type.lower().strip()
    results = []
    seen_keys = set()
    for inst in _mf_instruments:
        # Apply plan filter
        inst_plan = inst.get("plan", "").lower()
        if plan_filter and inst_plan != plan_filter:
            continue
        # Apply scheme type filter
        # Kite dividend_type: "growth", "payout", "reinvestment", "interim", "na", ""
        # "growth" or empty/"na" → Growth fund; anything else → IDCW/Dividend
        inst_div_type = inst.get("dividend_type", "").lower().strip()
        is_dividend = inst_div_type not in ("", "na", "growth")
        if type_filter:
            if type_filter == "growth" and is_dividend:
                continue
            if type_filter == "dividend" and not is_dividend:
                continue
        name_upper = inst["name"].upper()
        if not all(w in name_upper for w in words):
            continue
        # Deduplicate dividend variants (payout/reinvestment/interim)
        scheme_group = "dividend" if is_dividend else "growth"
        dedup_key = f"{inst['amc']}|{scheme_group}"
        if dedup_key in seen_keys:
            continue
        seen_keys.add(dedup_key)
        results.append({
            "tradingsymbol": inst["tradingsymbol"],
            "name": inst["name"],
            "amc": inst["amc"],
            "scheme_type": inst.get("scheme_type", ""),
            "plan": inst.get("plan", ""),
            "dividend_type": inst.get("dividend_type", ""),
            "last_price": inst["last_price"],
        })
        if len(results) >= 15:
            break
    if not results and q:
        # Debug: show what's being filtered out
        for inst in _mf_instruments[:5000]:
            name_upper = inst["name"].upper()
            if all(w in name_upper for w in words):
                logger.info(f"[MF-Search] Filtered out: {inst['name']} | plan={inst.get('plan','')} "
                      f"| scheme_type={inst.get('scheme_type','')} | dividend_type={inst.get('dividend_type','')} "
                      f"| filters: plan={plan_filter} type={type_filter}")
                break
    results.sort(key=lambda r: (
        0 if r.get("plan", "").lower() == "direct" else 1,
        0 if r.get("dividend_type", "").lower() in ("", "na", "growth") else 1,
        r["name"],
    ))
    return results


def get_mf_ltp(tradingsymbol: str) -> float:
    """Get last price for a mutual fund from cached instruments."""
    if not _mf_instruments_loaded:
        _load_mf_instruments()
    for inst in _mf_instruments:
        if inst["tradingsymbol"] == tradingsymbol:
            return inst["last_price"]
    return 0.0


# ═══════════════════════════════════════════════════════════
#  STOCK HISTORY (for charting)
# ═══════════════════════════════════════════════════════════

# Cache: {f"{symbol}.{exchange}.{period}" → {"data": [...], "fetched_at": float}}
_history_cache: Dict[str, dict] = {}
_history_cache_lock = threading.Lock()
_HISTORY_CACHE_TTL = 300  # 5 minutes


def fetch_stock_history(symbol: str, exchange: str, period: str = "1y", instrument_token: Optional[int] = None) -> Optional[List[dict]]:
    """Fetch OHLCV candle data for charting via Kite Historical Data API.

    Period mapping:
      1d  → 5minute,  today
      5d  → 15minute, 5 days
      1m  → day,      30 days
      6m  → day,      180 days
      ytd → day,      Jan 1 → today
      1y  → day,      365 days
      5y  → week,     5 years
      max → month,    20 years

    Returns list of {date, open, high, low, close, volume} dicts, or None on error.
    """
    if not is_session_valid():
        return None

    from datetime import datetime, timedelta

    now = datetime.now()
    to_date = now.strftime("%Y-%m-%d")
    period = period.lower()

    # Kite valid intervals: minute, 3minute, 5minute, 10minute, 15minute, 30minute, 60minute, day
    period_map = {
        "1d":  ("5minute",  timedelta(days=1)),
        "5d":  ("15minute", timedelta(days=5)),
        "1m":  ("day",      timedelta(days=30)),
        "6m":  ("day",      timedelta(days=180)),
        "1y":  ("day",      timedelta(days=365)),
        "5y":  ("day",      timedelta(days=5 * 365)),
        "max": ("day",      timedelta(days=20 * 365)),
    }

    if period == "ytd":
        interval = "day"
        from_date = f"{now.year}-01-01"
    elif period in period_map:
        interval, delta = period_map[period]
        from_date = (now - delta).strftime("%Y-%m-%d")
    else:
        return None

    # Check cache
    cache_key = f"{symbol.upper()}.{exchange.upper()}.{period}"
    with _history_cache_lock:
        cached = _history_cache.get(cache_key)
        if cached and (time.time() - cached["fetched_at"]) < _HISTORY_CACHE_TTL:
            return cached["data"]

    # Resolve instrument token
    token = instrument_token or _get_instrument_token(symbol.upper(), exchange.upper())
    if not token:
        return None

    path = f"/instruments/historical/{token}/{interval}"

    # For MAX period, fetch in 2000-day chunks (Kite limits daily candle range)
    if period == "max":
        all_candles = []
        chunk_days = 2000
        from_dt = now - timedelta(days=20 * 365)
        while from_dt < now:
            chunk_to = min(from_dt + timedelta(days=chunk_days), now)
            data = _api_get(path, {
                "from": from_dt.strftime("%Y-%m-%d"),
                "to": chunk_to.strftime("%Y-%m-%d"),
            })
            if data and "data" in data:
                all_candles.extend(data["data"].get("candles", []))
            from_dt = chunk_to + timedelta(days=1)
        candles = all_candles
    else:
        data = _api_get(path, {"from": from_date, "to": to_date})
        if not data or "data" not in data:
            return None
        candles = data["data"].get("candles", [])
    if not candles:
        return None

    # Candle format: [timestamp, open, high, low, close, volume]
    result = []
    for c in candles:
        if len(c) < 6:
            continue
        ts = c[0]
        # Normalize timestamp to string
        if hasattr(ts, 'isoformat'):
            date_str = ts.isoformat()
        else:
            date_str = str(ts)
        result.append({
            "date": date_str,
            "open": round(float(c[1]), 2),
            "high": round(float(c[2]), 2),
            "low": round(float(c[3]), 2),
            "close": round(float(c[4]), 2),
            "volume": int(c[5]),
        })

    # Downsample for long periods to keep chart performant
    if len(result) > 500 and period in ("5y", "max"):
        step = max(1, len(result) // 300)
        result = result[::step] + ([result[-1]] if result[-1] not in result[::step] else [])

    # Cache result
    with _history_cache_lock:
        _history_cache[cache_key] = {"data": result, "fetched_at": time.time()}

    return result


# ═══════════════════════════════════════════════════════════
#  STATUS
# ═══════════════════════════════════════════════════════════

def get_status() -> dict:
    """Get current Zerodha connection status."""
    return {
        "configured": is_configured(),
        "has_api_secret": bool(_api_secret),
        "has_access_token": bool(_access_token),
        "session_valid": is_session_valid(),
        "auth_failed": _auth_failed,
        "api_key_prefix": _api_key[:4] + "..." if _api_key else "",
        "token_prefix": _access_token[:4] + "..." if _access_token else "",
        "last_error": _last_error,
    }


def validate_session() -> bool:
    """Test if current access token works by hitting /user/profile."""
    if not is_session_valid():
        return False
    data = _api_get("/user/profile")
    if data and "data" in data:
        user = data["data"]
        name = user.get("user_name", "Unknown")
        logger.info(f"[Zerodha] Session valid — user: {name}")
        with _lock:
            global _session_valid
            _session_valid = True
        return True
    with _lock:
        _session_valid = False
    return False
